#ifndef _ENGINE_KEYS_H
#define _ENGINE_KEYS_H

#include <map>
#include "boost/assign.hpp"

enum Keys {
	K_F1, K_F2, K_F3, K_F4, K_F5, K_F6, K_F7, K_F8, K_F9, K_F10, K_F11, K_F12,
	K_0, K_1, K_2, K_3, K_4, K_5, K_6, K_7, K_8, K_9,
	K_A, K_B, K_C, K_D, K_E, K_F, K_G, K_H, K_I, K_J, K_K, K_L, K_M, K_N, K_O, K_P, K_Q, K_R, K_S, K_T, K_U, K_V, K_W, K_X, K_Y, K_Z,

	K_LSHIFT, K_RSHIFT,
	K_LCONTROL, K_RCONTROL,
	K_LMENU,K_RMENU,
	K_CAPITAL,

	K_TAB,
	K_BACK,
	K_BACKSLASH,
	K_DELETE,

	K_COMMA,
	K_PERIOD,
	K_SLASH,

	K_MINUS,
	K_EQUALS,

	K_SEMICOLON,
	K_APOSTROPHE,

	K_LBRACKET,
	K_RBRACKET,

	K_SPACE,
	K_RETURN,
	K_ESCAPE,

	K_LEFT, K_RIGHT,
	K_UP, K_DOWN,
	K_PGDOWN, K_PGUP,

	K_MLEFT, K_MRIGHT, K_MMIDDLE
};

std::map<OIS::KeyCode,Keys> keyList = 
boost::assign::map_list_of
	(OIS::KC_F1,K_F1) (OIS::KC_F2,K_F2) (OIS::KC_F3,K_F3) (OIS::KC_F4,K_F4) (OIS::KC_F5,K_F5) (OIS::KC_F6,K_F6) (OIS::KC_F7,K_F7) (OIS::KC_F8,K_F8) (OIS::KC_F9,K_F9) (OIS::KC_F10,K_F10) (OIS::KC_F11,K_F11) (OIS::KC_F12,K_F12)
	(OIS::KC_0,K_0) (OIS::KC_1,K_1) (OIS::KC_2,K_2) (OIS::KC_3,K_3) (OIS::KC_4,K_4) (OIS::KC_5,K_5) (OIS::KC_6,K_6) (OIS::KC_7,K_7) (OIS::KC_8,K_8) (OIS::KC_9,K_9)
	(OIS::KC_A,K_A) (OIS::KC_B,K_B) (OIS::KC_C,K_C) (OIS::KC_D,K_D) (OIS::KC_E,K_E) (OIS::KC_F,K_F) (OIS::KC_G,K_G) (OIS::KC_H,K_H) (OIS::KC_I,K_I) (OIS::KC_J,K_J) (OIS::KC_K,K_K) (OIS::KC_L,K_L) (OIS::KC_M,K_M) (OIS::KC_N,K_N) (OIS::KC_O,K_O) (OIS::KC_P,K_P) (OIS::KC_Q,K_Q) (OIS::KC_R,K_R) (OIS::KC_S,K_S) (OIS::KC_T,K_T) (OIS::KC_U,K_U) (OIS::KC_V,K_V) (OIS::KC_W,K_W) (OIS::KC_X,K_X) (OIS::KC_Y,K_Y) (OIS::KC_Z,K_Z)

	(OIS::KC_LSHIFT,K_LSHIFT) (OIS::KC_RSHIFT,K_RSHIFT)
	(OIS::KC_LCONTROL,K_LCONTROL) (OIS::KC_RCONTROL,K_RCONTROL)
	(OIS::KC_LMENU,K_LMENU)(OIS::KC_RMENU,K_RMENU)
	(OIS::KC_CAPITAL,K_CAPITAL)

	(OIS::KC_TAB,K_TAB)
	(OIS::KC_BACK,K_BACK)
	(OIS::KC_BACKSLASH,K_BACKSLASH)
	(OIS::KC_DELETE,K_DELETE)

	(OIS::KC_COMMA,K_COMMA)
	(OIS::KC_PERIOD,K_PERIOD)
	(OIS::KC_SLASH,K_SLASH)

	(OIS::KC_MINUS,K_MINUS)
	(OIS::KC_EQUALS,K_EQUALS)

	(OIS::KC_SEMICOLON,K_SEMICOLON)
	(OIS::KC_APOSTROPHE,K_APOSTROPHE)

	(OIS::KC_LBRACKET,K_LBRACKET)
	(OIS::KC_RBRACKET,K_RBRACKET)

	(OIS::KC_SPACE,K_SPACE)
	(OIS::KC_RETURN,K_RETURN)
	(OIS::KC_ESCAPE,K_ESCAPE)

	(OIS::KC_LEFT,K_LEFT) (OIS::KC_RIGHT,K_RIGHT)
	(OIS::KC_UP,K_UP) (OIS::KC_DOWN,K_DOWN)
	(OIS::KC_PGDOWN,K_PGDOWN) (OIS::KC_PGUP,K_PGUP)

	//(OIS::KC_MLEFT,K_MLEFT) (OIS::KC_MRIGHT,K_MRIGHT) 
;

#endif
