#ifndef _ENGINE_KEYS_H
#define _ENGINE_KEYS_H


#define OIS_DYNAMIC_LIB
#include <OIS/OIS.h>

enum Keys {
	K_NOP,
	K_F1, K_F2, K_F3, K_F4, K_F5, K_F6, K_F7, K_F8, K_F9, K_F10, K_F11, K_F12,
	K_0, K_1, K_2, K_3, K_4, K_5, K_6, K_7, K_8, K_9,
	K_A, K_B, K_C, K_D, K_E, K_F, K_G, K_H, K_I, K_J, K_K, K_L, K_M, K_N, K_O, K_P, K_Q, K_R, K_S, K_T, K_U, K_V, K_W, K_X, K_Y, K_Z,

	K_LSHIFT, K_RSHIFT,
	K_LCONTROL, K_RCONTROL,
	K_LMENU,K_RMENU,
	K_CAPITAL,

	K_TAB,
	K_BACK,
	K_BACKSLASH,
	K_DELETE,

	K_COMMA,
	K_PERIOD,
	K_SLASH,

	K_MINUS,
	K_EQUALS,

	K_SEMICOLON,
	K_APOSTROPHE,

	K_LBRACKET,
	K_RBRACKET,

	K_SPACE,
	K_RETURN,
	K_ESCAPE,

	K_LEFT, K_RIGHT,
	K_UP, K_DOWN,
	K_PGDOWN, K_PGUP,

	K_MLEFT, K_MRIGHT, K_MMIDDLE,

	K_FOCUS_CHANGE
};


#endif
